### ISSUE TITLE
Updates no longer apply, version json has changed

### ISSUE THREAD

**Issue by Joly0** [imagegenius/docker-amp#10]
Hey, just so you know, https://cubecoders.com/AMPVersions.json is no longer updated. The updated json file with the current version is here https://downloads.cubecoders.com/AMP/manifest.json. This docker container is several versions behind. This container is on version 2.4.4.0, the latest ist 2.4.6.10

**Comment by Joly0** [comment]
https://github.com/MitchTalmadge/AMP-dockerized/issues/164#issuecomment-1806616243
This might help

**Comment by hydazz** [comment]
thanks for pointing this out, ill update the json endpoint, and so some other housecleaning
