### ISSUE TITLE
Unraid Install Package Issue 

### ISSUE THREAD

**Issue by mikixiv** [imagegenius/docker-amp#18]
![image](https://github.com/user-attachments/assets/e6a3b072-3fd6-4a93-b43c-af6139be8eb2)

**Comment by mikixiv** [comment]
Run successfully after manual installation libicu-dev
![image](https://github.com/user-attachments/assets/a72221a6-3137-4c4b-a3b8-e591f2ac0db0)
![image](https://github.com/user-attachments/assets/13117992-8fde-4b37-867a-9476ac04f222)

**Comment by hydazz** [comment]
Thanks, added https://github.com/imagegenius/docker-amp/commit/5c3c676fc69bbb85cab84fcab37b0e6731f69b68
