### ISSUE TITLE
Java not installed

### ISSUE THREAD

**Issue by cproxy** [imagegenius/docker-amp#3]
AMP reports java not installed for Minecraft

I've supplied the docker config with multiple versions.

> Installing versions of java: openjdk17-jre openjdk13-jre openjdk9-jre openjdk8-jre openjdk7-jre 
> [custom-init] No custom files found, skipping...
> [Info] AMP Instance Manager v2.4.1.2 built 21/12/2022 17:55
> [Info] Release spec: Release - built by CUBECODERS/buildbot on CCL-DEV
> [Info] Waiting for AMP instance to start...
> [Notice] AMP instance Main is now running.

`'java' is not installed, or not available in PATH. Please make sure Java 8 is installed on your system. If you have just installed Java then you will need to restart AMP.`

**Comment by hydazz** [comment]
Update the image and lmk if its fixed :)
